/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mybookcollection;

import javax.swing.JOptionPane;

/**
 *
 * @author izyan
 */
public class custom_profil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(custom_profil.class.getName());

    /**
     * Creates new form form_user
     */
    public custom_profil() {
        initComponents();
        
        if (CurrentUser.isLoggedIn()) {
           jTextField1.setText(CurrentUser.username);
        }
    }
    
    private void simpanUsernameBaru() {
    String newUsername = jTextField1.getText().trim();

    if (newUsername.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        CurrentUser.username = newUsername;

        java.io.File file = new java.io.File("users.txt");
        java.util.List<String> lines = java.nio.file.Files.readAllLines(file.toPath());
        java.util.List<String> updatedLines = new java.util.ArrayList<>();

        for (String line : lines) {
            String[] parts = line.split(":", 2);
            if (parts.length == 2 && parts[0].equals(newUsername)) {
                continue;
            } else if (parts.length == 2 && parts[0].equals(CurrentUser.username)) {
                updatedLines.add(newUsername + ":" + parts[1]);
            } else {
                updatedLines.add(line);
            }
        }

        java.nio.file.Files.write(file.toPath(), updatedLines);

        JOptionPane.showMessageDialog(this, "Username berhasil diubah!");

        this.dispose(); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan perubahan.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        berandaBtn = new javax.swing.JButton();
        SimpanBtn2 = new javax.swing.JButton();
        BatalBtn1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        jLabel5.setText("NAMA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jLabel1.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setFont(new java.awt.Font("PT Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("PROFIL");

        jLabel2.setBackground(new java.awt.Color(204, 153, 0));
        jLabel2.setFont(new java.awt.Font("Serif", 2, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("pemilik perpus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 30));

        berandaBtn.setFont(new java.awt.Font("PT Serif", 3, 18)); // NOI18N
        berandaBtn.setForeground(new java.awt.Color(204, 153, 0));
        berandaBtn.setText("Beranda");
        berandaBtn.addActionListener(this::berandaBtnActionPerformed);
        getContentPane().add(berandaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, -1));

        SimpanBtn2.setBackground(new java.awt.Color(204, 255, 204));
        SimpanBtn2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        SimpanBtn2.setForeground(new java.awt.Color(0, 102, 0));
        SimpanBtn2.setText("SIMPAN");
        SimpanBtn2.addActionListener(this::SimpanBtn2ActionPerformed);
        getContentPane().add(SimpanBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        BatalBtn1.setBackground(new java.awt.Color(255, 51, 51));
        BatalBtn1.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        BatalBtn1.setText("BATAL");
        BatalBtn1.setAutoscrolls(true);
        BatalBtn1.addActionListener(this::BatalBtn1ActionPerformed);
        getContentPane().add(BatalBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mybookcollection/images/bgmenuubahdatabuku.png"))); // NOI18N
        bg.setText("jLabel6");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaBtnActionPerformed
        // TODO add your handling code here:
        MainPage rg = new MainPage();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setResizable(false);
        
        this.dispose();
    }//GEN-LAST:event_berandaBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SimpanBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBtn2ActionPerformed

        // TODO add your handling code here:
        simpanUsernameBaru();
        
        MainPage rg = new MainPage();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setResizable(false);
        
        this.dispose();
    }//GEN-LAST:event_SimpanBtn2ActionPerformed

    private void BatalBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalBtn1ActionPerformed
        // TODO add your handling code here:
        
        MainPage rg = new MainPage();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setResizable(false);
        
        this.dispose();
    }//GEN-LAST:event_BatalBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new custom_profil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalBtn1;
    private javax.swing.JButton SimpanBtn2;
    private javax.swing.JButton berandaBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
