/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mybookcollection;

import javax.swing.JOptionPane;

/**
 *
 * @author riaastuti
 */
public class dataBuku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dataBuku.class.getName());

    /**
     * Creates new form MainPage
     */
    public dataBuku() {
    initComponents();
    if (CurrentUser.isLoggedIn()) {
        NAMALabel1.setText(CurrentUser.username); 
    }
    loadDataBuku();
    updateJumlahBuku();
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NAMALabel1 = new javax.swing.JLabel();
        kembaliBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tambahBtn = new javax.swing.JButton();
        hapuskurangiBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JumlahBukuLabel2 = new javax.swing.JLabel();
        bgtextmybookcollection = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bgmainlibrary = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        NAMALabel1.setForeground(new java.awt.Color(255, 255, 255));
        NAMALabel1.setText(CurrentUser.username);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NAMALabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAMALabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 410, 30));

        kembaliBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        kembaliBtn.setForeground(new java.awt.Color(204, 153, 0));
        kembaliBtn.setText("BERANDA");
        kembaliBtn.addActionListener(this::kembaliBtnActionPerformed);
        getContentPane().add(kembaliBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        tambahBtn.setBackground(new java.awt.Color(204, 255, 204));
        tambahBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tambahBtn.setForeground(new java.awt.Color(0, 102, 0));
        tambahBtn.setText("+TAMBAH");
        tambahBtn.addActionListener(this::tambahBtnActionPerformed);

        hapuskurangiBtn.setBackground(new java.awt.Color(255, 204, 204));
        hapuskurangiBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        hapuskurangiBtn.setForeground(new java.awt.Color(204, 0, 0));
        hapuskurangiBtn.setText("- HAPUS/KURANGI");
        hapuskurangiBtn.addActionListener(this::hapuskurangiBtnActionPerformed);

        jTable1.setBackground(new java.awt.Color(255, 255, 153));
        jTable1.setFont(new java.awt.Font("Hoefler Text", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "JUDUL", "KODE", "PENERBIT", "PENGARANG", "TAHUN TERBIT", "LOKASI"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        JumlahBukuLabel2.setText("Jumlah Buku : 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tambahBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapuskurangiBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JumlahBukuLabel2)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(hapuskurangiBtn)
                    .addComponent(JumlahBukuLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 660, 320));

        bgtextmybookcollection.setBackground(new java.awt.Color(102, 51, 0));

        jLabel3.setFont(new java.awt.Font("PT Serif", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 153, 0));
        jLabel3.setText("DATA");

        jLabel4.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEMUA BUKU");

        javax.swing.GroupLayout bgtextmybookcollectionLayout = new javax.swing.GroupLayout(bgtextmybookcollection);
        bgtextmybookcollection.setLayout(bgtextmybookcollectionLayout);
        bgtextmybookcollectionLayout.setHorizontalGroup(
            bgtextmybookcollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgtextmybookcollectionLayout.createSequentialGroup()
                .addGroup(bgtextmybookcollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgtextmybookcollectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(bgtextmybookcollectionLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        bgtextmybookcollectionLayout.setVerticalGroup(
            bgtextmybookcollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgtextmybookcollectionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(bgtextmybookcollection, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 80));

        bgmainlibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mybookcollection/images/bahanbgmainnetbeans.png"))); // NOI18N
        bgmainlibrary.setText("jLabel1");
        getContentPane().add(bgmainlibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        // TODO add your handling code here:
        MainPage rg = new MainPage();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setResizable(false);
        
        this.dispose();
    }//GEN-LAST:event_kembaliBtnActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        Form_tambah_buku rg = new Form_tambah_buku();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setResizable(false);
        
        this.dispose();
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void hapuskurangiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuskurangiBtnActionPerformed
        // TODO add your handling code here:
        hapusDataBuku();
    }//GEN-LAST:event_hapuskurangiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dataBuku().setVisible(true));
    }
    
    private void loadDataBuku() {
    try {
        java.io.File file = new java.io.File("buku.txt");
        
        if (!file.exists()) {
            file.createNewFile();
        }

        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);

        java.util.Scanner scanner = new java.util.Scanner(file);
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine().trim();
            if (line.isEmpty()) continue; // lewati baris kosong

            String[] parts = line.split(";", -1); // -1 agar tidak potong empty field

            if (parts.length == 6) {
                model.addRow(parts); // tambahkan ke tabel
            }
        }
        scanner.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data buku.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void hapusDataBuku() {
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        String judul = (String) jTable1.getValueAt(selectedRow, 0);
        String kode = (String) jTable1.getValueAt(selectedRow, 1);
        String penerbit = (String) jTable1.getValueAt(selectedRow, 2);
        String pengarang = (String) jTable1.getValueAt(selectedRow, 3);
        String tahun = (String) jTable1.getValueAt(selectedRow, 4);
        String lokasi = (String) jTable1.getValueAt(selectedRow, 5);

        String dataToDelete = judul + ";" + kode + ";" + penerbit + ";" + pengarang + ";" + tahun + ";" + lokasi;

        java.io.File file = new java.io.File("buku.txt");
        java.util.List<String> lines = java.nio.file.Files.readAllLines(file.toPath());
        java.util.List<String> updatedLines = new java.util.ArrayList<>();

        for (String line : lines) {
            if (!line.trim().equals(dataToDelete)) {
                updatedLines.add(line);
            }
        }

        java.nio.file.Files.write(file.toPath(), updatedLines);

        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.removeRow(selectedRow);

        updateJumlahBuku();
        
        JOptionPane.showMessageDialog(this, "Data buku berhasil dihapus!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data buku.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void updateJumlahBuku() {
    int rowCount = jTable1.getRowCount();
    JumlahBukuLabel2.setText("Jumlah Buku: " + rowCount);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JumlahBukuLabel2;
    private javax.swing.JLabel NAMALabel1;
    private javax.swing.JLabel bgmainlibrary;
    private javax.swing.JPanel bgtextmybookcollection;
    private javax.swing.JButton hapuskurangiBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JButton tambahBtn;
    // End of variables declaration//GEN-END:variables
}
