/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mybookcollection;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author izyan
 */
public class form_tambah_peminjam extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_tambah_peminjam.class.getName());

    /**
     * Creates new form form_user
     */
    public form_tambah_peminjam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        KodeBukuTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NamaTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        berandaBtn = new javax.swing.JButton();
        SimpanBtn2 = new javax.swing.JButton();
        WaktuAmbilDateChooser1 = new com.toedter.calendar.JDateChooser();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        jLabel5.setText("NAMA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel4.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        jLabel4.setText("NO. ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        jLabel6.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        jLabel6.setText("KODE BUKU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        KodeBukuTextField.addActionListener(this::KodeBukuTextFieldActionPerformed);
        getContentPane().add(KodeBukuTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 290, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        jLabel7.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        jLabel7.setText("WAKTU AKHIR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 30));

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jLabel1.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setFont(new java.awt.Font("PT Serif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("TAMBAH");

        jLabel2.setBackground(new java.awt.Color(204, 153, 0));
        jLabel2.setFont(new java.awt.Font("Serif", 2, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" peminjam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 70));
        getContentPane().add(NamaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 290, 30));
        getContentPane().add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 30));

        berandaBtn.setFont(new java.awt.Font("PT Serif", 3, 18)); // NOI18N
        berandaBtn.setForeground(new java.awt.Color(204, 153, 0));
        berandaBtn.setText("Kembali");
        berandaBtn.addActionListener(this::berandaBtnActionPerformed);
        getContentPane().add(berandaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, -1));

        SimpanBtn2.setBackground(new java.awt.Color(204, 255, 204));
        SimpanBtn2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        SimpanBtn2.setForeground(new java.awt.Color(0, 102, 0));
        SimpanBtn2.setText("SIMPAN");
        SimpanBtn2.addActionListener(this::SimpanBtn2ActionPerformed);
        getContentPane().add(SimpanBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));
        getContentPane().add(WaktuAmbilDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 222, 290, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mybookcollection/images/bgmenuubahdatabuku.png"))); // NOI18N
        bg.setText("jLabel6");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaBtnActionPerformed
        // TODO add your handling code here:
        dataPeminjaman rg = new dataPeminjaman();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setResizable(false);
        
     
        this.dispose();
    }//GEN-LAST:event_berandaBtnActionPerformed

    private void SimpanBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBtn2ActionPerformed
        // TODO add your handling code here:
        String nomorIDstr = IDTextField.getText().trim();
        String nama = NamaTextField.getText().trim();
        String kodeBuku = KodeBukuTextField.getText().trim();
        Date selectedDate = WaktuAmbilDateChooser1.getDate();
        
        if (selectedDate == null) {
        JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(selectedDate);
        
         if (nomorIDstr.isEmpty() || nama.isEmpty() || kodeBuku.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
       if (!validasiDataPeminjaman(nomorIDstr, nama, kodeBuku)) {
        return;
    }  
        try {
        java.io.FileWriter fw = new java.io.FileWriter("peminjaman.txt", true);
        fw.write(nomorIDstr + ";" + nama + ";" + kodeBuku + ";" + tanggal + "\n");
        fw.close();

        JOptionPane.showMessageDialog(this, "Data peminjaman berhasil disimpan!");

        dataPeminjaman dp = new dataPeminjaman();
        dp.setVisible(true);
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data peminjaman.", "Error", JOptionPane.ERROR_MESSAGE);
    }
       
    }//GEN-LAST:event_SimpanBtn2ActionPerformed

    private void KodeBukuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeBukuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeBukuTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new form_tambah_peminjam().setVisible(true));
    }
    
    private boolean validasiDataPeminjaman(String nomorIDstr, String nama, String kodeBuku) {
    int NomorID;
    try {
        NomorID = Integer.parseInt(nomorIDstr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "NO. ID harus benar", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    boolean idDitemukan = false;
    boolean namaSesuai = false;

    try {
        java.io.File fileAnggota = new java.io.File("anggota.txt");
        if (!fileAnggota.exists()) {
            JOptionPane.showMessageDialog(this, "File data anggota tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        java.util.Scanner scanner = new java.util.Scanner(fileAnggota);
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine().trim();
            if (line.isEmpty()) continue;

            String[] parts = line.split(";", -1);
            if (parts.length >= 2) {
                try {
                    int idFile = Integer.parseInt(parts[0]);
                    String namaFile = parts[1];

                    if (idFile == NomorID) {
                        idDitemukan = true;
                        if (namaFile.equals(nama)) {
                            namaSesuai = true;
                        }
                        break;
                    }
                } catch (NumberFormatException ignored) {
                }
            }
        }
        scanner.close();

        if (!idDitemukan) {
            JOptionPane.showMessageDialog(this, "Tidak ada nomor ID tersebut di data anggota.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!namaSesuai) {
            JOptionPane.showMessageDialog(this, "Nama tidak sesuai dengan nomor ID di data anggota.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal membaca data anggota.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    boolean kodeDitemukan = false;
    try {
        java.io.File fileBuku = new java.io.File("buku.txt");
        if (!fileBuku.exists()) {
            JOptionPane.showMessageDialog(this, "File data buku tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        java.util.Scanner scanner = new java.util.Scanner(fileBuku);
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine().trim();
            if (line.isEmpty()) continue;

            String[] parts = line.split(";", -1);
            if (parts.length >= 2) {
                String kodeFile = parts[1]; // kolom ke-2 = kode buku
                if (kodeFile.equals(kodeBuku)) {
                    kodeDitemukan = true;
                    break;
                }
            }
        }
        scanner.close();

        if (!kodeDitemukan) {
            JOptionPane.showMessageDialog(this, "Buku tidak ada di data buku.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal membaca data buku.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField KodeBukuTextField;
    private javax.swing.JTextField NamaTextField;
    private javax.swing.JButton SimpanBtn2;
    private com.toedter.calendar.JDateChooser WaktuAmbilDateChooser1;
    private javax.swing.JButton berandaBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
